[toolchain]
anchor_version = "0.30.1"
solana_version = "2.2.21"

[features]
seeds = false
skip-lint = false

[programs.localnet]
investor_fee_distributor = "4uZxW8UrmijWukHwDShTqwc8EyhQxJ5rxaijnVXKbZaF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\ADMIN\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
